### ISSUE TITLE
.OVA KALI IMPORT FAILED

### ISSUE THREAD

**Issue by Midside** [sagishahar/lpeworkshop#7]
Kali 2016.2 x64 (Workshop).ova' (VERR_INVALID_NAME): RTManifestEntrySetAttr(,'Kali 2016.2 x64 (Workshop).ovf','SHA1', 'b18eb1426287e8db7a01930b8cf9db0bae3166bc', 0x4) failed on line 1: VERR_INVALID_NAME.

**Comment by sagishahar** [comment]
The information you've provided is not enough to understand the root cause. Regardless, make sure that the file was downloaded successfully. 

MD5: c7da9b97779cb441c281657233cd1cb6
SHA1: 7033c023c8756a0c48198be1b2fb4b18c7edff53

The file was imported successfully with VMware Fusion Professional Version 12.1.1.
