### ISSUE TITLE
Running the script on a non-US Windows box doesn't work

### ISSUE THREAD

**Issue by 1989gironimo** [sagishahar/lpeworkshop#8]
You have to replace
`:: Check if the script is running in a high integrity context
whoami /groups | findstr /i /c:"high level Mandatory" >nul && (
   goto main`

to 

`:: Check if the script is running in a high integrity context
whoami /groups | findstr /i /c:"Administrator" >nul && (
   goto main`

**Comment by sagishahar** [comment]
Thanks for your suggestion and sorry it took a very long time to respond.

Unfortunately, your suggestion will cause similar issue to non-US Windows as the Administrator account name can be localized. For example,  French-based Windows would have Administrateur rather than Administrator. 

Please see this for more information: https://social.technet.microsoft.com/wiki/contents/articles/13813.localized-names-for-administrator-account-in-windows.aspx
